forecastguard_dbt:
  target: dev

  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: forecastguard
      password: forecastguard
      dbname: forecastguard
      schema: analytics
      threads: 4
